/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AsyncDemo {
    }
    interface ControllerDemo {
    }
    interface CounterDemo {
    }
    interface MixinDemo {
    }
    interface PreviousDemo {
    }
    interface StoreDemo {
    }
    interface WatchEffectDemo {
    }
    interface WatchExplicitDemo {
    }
}
declare global {
    interface HTMLAsyncDemoElement extends Components.AsyncDemo, HTMLStencilElement {
    }
    var HTMLAsyncDemoElement: {
        prototype: HTMLAsyncDemoElement;
        new (): HTMLAsyncDemoElement;
    };
    interface HTMLControllerDemoElement extends Components.ControllerDemo, HTMLStencilElement {
    }
    var HTMLControllerDemoElement: {
        prototype: HTMLControllerDemoElement;
        new (): HTMLControllerDemoElement;
    };
    interface HTMLCounterDemoElement extends Components.CounterDemo, HTMLStencilElement {
    }
    var HTMLCounterDemoElement: {
        prototype: HTMLCounterDemoElement;
        new (): HTMLCounterDemoElement;
    };
    interface HTMLMixinDemoElement extends Components.MixinDemo, HTMLStencilElement {
    }
    var HTMLMixinDemoElement: {
        prototype: HTMLMixinDemoElement;
        new (): HTMLMixinDemoElement;
    };
    interface HTMLPreviousDemoElement extends Components.PreviousDemo, HTMLStencilElement {
    }
    var HTMLPreviousDemoElement: {
        prototype: HTMLPreviousDemoElement;
        new (): HTMLPreviousDemoElement;
    };
    interface HTMLStoreDemoElement extends Components.StoreDemo, HTMLStencilElement {
    }
    var HTMLStoreDemoElement: {
        prototype: HTMLStoreDemoElement;
        new (): HTMLStoreDemoElement;
    };
    interface HTMLWatchEffectDemoElement extends Components.WatchEffectDemo, HTMLStencilElement {
    }
    var HTMLWatchEffectDemoElement: {
        prototype: HTMLWatchEffectDemoElement;
        new (): HTMLWatchEffectDemoElement;
    };
    interface HTMLWatchExplicitDemoElement extends Components.WatchExplicitDemo, HTMLStencilElement {
    }
    var HTMLWatchExplicitDemoElement: {
        prototype: HTMLWatchExplicitDemoElement;
        new (): HTMLWatchExplicitDemoElement;
    };
    interface HTMLElementTagNameMap {
        "async-demo": HTMLAsyncDemoElement;
        "controller-demo": HTMLControllerDemoElement;
        "counter-demo": HTMLCounterDemoElement;
        "mixin-demo": HTMLMixinDemoElement;
        "previous-demo": HTMLPreviousDemoElement;
        "store-demo": HTMLStoreDemoElement;
        "watch-effect-demo": HTMLWatchEffectDemoElement;
        "watch-explicit-demo": HTMLWatchExplicitDemoElement;
    }
}
declare namespace LocalJSX {
    interface AsyncDemo {
    }
    interface ControllerDemo {
    }
    interface CounterDemo {
    }
    interface MixinDemo {
    }
    interface PreviousDemo {
    }
    interface StoreDemo {
    }
    interface WatchEffectDemo {
    }
    interface WatchExplicitDemo {
    }
    interface IntrinsicElements {
        "async-demo": AsyncDemo;
        "controller-demo": ControllerDemo;
        "counter-demo": CounterDemo;
        "mixin-demo": MixinDemo;
        "previous-demo": PreviousDemo;
        "store-demo": StoreDemo;
        "watch-effect-demo": WatchEffectDemo;
        "watch-explicit-demo": WatchExplicitDemo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "async-demo": LocalJSX.IntrinsicElements["async-demo"] & JSXBase.HTMLAttributes<HTMLAsyncDemoElement>;
            "controller-demo": LocalJSX.IntrinsicElements["controller-demo"] & JSXBase.HTMLAttributes<HTMLControllerDemoElement>;
            "counter-demo": LocalJSX.IntrinsicElements["counter-demo"] & JSXBase.HTMLAttributes<HTMLCounterDemoElement>;
            "mixin-demo": LocalJSX.IntrinsicElements["mixin-demo"] & JSXBase.HTMLAttributes<HTMLMixinDemoElement>;
            "previous-demo": LocalJSX.IntrinsicElements["previous-demo"] & JSXBase.HTMLAttributes<HTMLPreviousDemoElement>;
            "store-demo": LocalJSX.IntrinsicElements["store-demo"] & JSXBase.HTMLAttributes<HTMLStoreDemoElement>;
            "watch-effect-demo": LocalJSX.IntrinsicElements["watch-effect-demo"] & JSXBase.HTMLAttributes<HTMLWatchEffectDemoElement>;
            "watch-explicit-demo": LocalJSX.IntrinsicElements["watch-explicit-demo"] & JSXBase.HTMLAttributes<HTMLWatchExplicitDemoElement>;
        }
    }
}
